draft/draft-ietf-idr-bgp-model.xml
src/validate-and-gen-trees.sh
src/yang/ietf-bgp-policy.yang
src/yang/ietf-bgp.yang

This commit tries to take care of some nits.

Address a few final changes

---

src/yang/ietf-bgp-rib-tables.yang

Resolve syntax errors of prior issue 122 push.
Resolves #122

Issue 122: Fix syntax errors of prior push

---

src/yang/ietf-bgp-types.yang
src/yang/ietf-bgp.yang

Issue 85: clear bgp needs additional arguments

Issue 85: clear bgp needs additional arguments

---

draft/draft-ietf-idr-bgp-model.xml
src/validate-and-gen-trees.sh
src/yang/ietf-bgp.yang

Issue #153. Fix the config false statement in last-error

---

src/yang/ietf-bgp-common-multiprotocol.yang
src/yang/ietf-bgp-common.yang

Mismatch of default enabled configuration for graceful restart

---

Dockerfile
draft/draft-ietf-idr-bgp-model.xml
src/validate-and-gen-trees.sh

Issue #163.
I know it has more than the consensus commit, but it is more work trying to remove the fixes for the Docker build.

Fix consensus status in the draft.

---

src/yang/ietf-bgp-types.yang

Issue 64: Update references from RFC 3107 to RFC 8277

---

src/yang/ietf-bgp-policy.yang

Although issue #168 calls for set next-hop, this commit is for match next-hop.

Add support for match next-hop

---

src/yang/ietf-bgp-rib.yang

Issue 131: Model RFC 2545 link-local nexthops.

---

src/yang/ietf-bgp-rib-tables.yang

#195: grouping bgp-adj-rib-in-post-route-annotations-state - correction

---

src/yang/ietf-bgp-types.yang

First crack at sorting the feature set. Issue #126

Issue #126 Sort the features

---

.gitignore
src/yang/ietf-bgp-policy.yang
src/yang/ietf-bgp-rib-attributes.yang
src/yang/ietf-bgp-rib.yang

This PR addresses part of #79, #66

Address issue #89, #79 and #66

---

src/yang/ietf-bgp-common.yang

Add a global level statistics container and per afi-safi within global

---

src/yang/ietf-bgp-policy.yang

Fix the name of the leaf

---

src/yang/ietf-bgp-neighbor.yang
src/yang/ietf-bgp.yang

Move config false statement to the top of stats container

---

src/yang/ietf-bgp-common.yang

Remove 'clear action' option on prefixes and paths

---

draft/draft-ietf-idr-bgp-model.xml
src/yang/example-bgp-configuration-a.1.2.xml

Update AO example

---

draft/draft-ietf-idr-bgp-model.xml

Minor editorial comments to reflect changes in the draft.

Update draft to reflect content

---

src/yang/ietf-bgp-common.yang

Address issue #82

---

draft/Makefile
draft/draft-ietf-idr-bgp-model.xml
src/download-dependent-models.py
src/validate-and-gen-trees.sh
src/yang/example-bgp-configuration-a.1.1.xml
src/yang/example-bgp-configuration-a.1.2.xml
src/yang/ietf-bgp-common.yang
src/yang/ietf-bgp.yang

A few changes. Used the TCP MSS type definition from TCP YANG module.
While at it, cleaned up TCP-AO and TCP-MD5 configuration and examples. @jhaas-pfrc, please review carefully to make sure that this is what you wanted.

Issue #221 TCP MSS and PMTUD

---

draft/draft-ietf-idr-bgp-model.xml
src/download-dependent-models.py
src/yang/ietf-bgp.yang

Update reference to BFD YANG model.

---

draft/draft-ietf-idr-bgp-model.xml
src/yang/example-bgp-configuration-a.1.2.xml
src/yang/ietf-bgp.yang

Make RFCs 2385, 4451, 6151 informative references. 
Adjust too-long line issues flagged by xml2rfc.

Issue 238 - Address xml2rfc errors

---

src/yang/iana-bgp-types.yang
src/yang/ietf-bgp-policy.yang

bgp-ext-community-type without qualifier is ambiguous

---

src/yang/iana-bgp-types.yang
src/yang/ietf-bgp-common-multiprotocol.yang
src/yang/ietf-bgp-common-structure.yang
src/yang/ietf-bgp-common.yang
src/yang/ietf-bgp-neighbor.yang
src/yang/ietf-bgp-policy.yang
src/yang/ietf-bgp-rib-attributes.yang
src/yang/ietf-bgp-rib-tables.yang
src/yang/ietf-bgp-rib-types.yang
src/yang/ietf-bgp-rib.yang
src/yang/ietf-bgp.yang

Issue 240 - update copyright dates

---

src/yang/ietf-bgp-policy.yang

Remove tab in the YANG module.

---

src/yang/ietf-bgp-common-structure.yang
src/yang/ietf-bgp-common.yang
src/yang/ietf-bgp.yang

Issue #259 - Rehome ebgp-multihop under transport

---

draft/draft-ietf-idr-bgp-model.xml
src/yang/example-newafi-bgp.yang
src/yang/example-newco-bgp-a.2.yang
src/yang/iana-bgp-types.yang
src/yang/ietf-bgp-common-multiprotocol.yang
src/yang/ietf-bgp-common-structure.yang
src/yang/ietf-bgp-common.yang
src/yang/ietf-bgp-neighbor.yang
src/yang/ietf-bgp-policy.yang
src/yang/ietf-bgp-rib-attributes.yang
src/yang/ietf-bgp-rib-tables.yang
src/yang/ietf-bgp-rib-types.yang
src/yang/ietf-bgp-rib.yang
src/yang/ietf-bgp.yang

Update the title of the draft.

---

src/yang/ietf-bgp-common.yang
src/yang/ietf-bgp.yang

Issue #257 - move ttl-security under transport container

---

src/yang/ietf-bgp.yang

Issue #302 - Move peer-group configuration to top of bgp/neighbors

---

src/yang/ietf-bgp-common-multiprotocol.yang
src/yang/ietf-bgp-neighbor.yang
src/yang/ietf-bgp.yang

Issue #294 - Remove graceful-restart operational state from peer-groups

---

src/yang/ietf-bgp-common-structure.yang
src/yang/ietf-bgp.yang

Issue #300 - add-paths is missing at afi-safis level configuration

---

src/yang/ietf-bgp-policy.yang

Issue #284 - Refactor equality operations from policy

---

src/yang/ietf-bgp-policy.yang

Aesthetic cleanup.
Closes #262

Issue #262 move as-path-sets to top of matches

---

src/yang/ietf-bgp-common-multiprotocol.yang
src/yang/ietf-bgp-common-structure.yang
src/yang/ietf-bgp.yang

Fix merge issues from Issue #281.
Closes #331

Issue #331 Fix build break

---

src/yang/iana-bgp-community-types.yang

Bad merge in Issue #306 lost this work.
Closes #330

Issue #330 Restore community regexp documentation lost in merge

---

draft/draft-ietf-idr-bgp-model.xml
src/yang/iana-bgp-community-types.yang
src/yang/ietf-bgp-policy.yang
src/yang/ietf-bgp-rib-attributes.yang
src/yang/ietf-bgp-rib.yang

Issue #329 Add RFC 5701 IPv6 extended community support

---

draft/draft-ietf-idr-bgp-model.xml
src/yang/ietf-bgp-rib-tables.yang
src/yang/ietf-bgp-rib.yang

Fix text for loc-rib to reflect that it's only for one route.

---

src/yang/ietf-bgp-capabilities.yang
src/yang/ietf-bgp-common-multiprotocol.yang
src/yang/ietf-bgp-common-structure.yang
src/yang/ietf-bgp-common.yang
src/yang/ietf-bgp-neighbor.yang
src/yang/ietf-bgp-rib-attributes.yang
src/yang/ietf-bgp-rib-tables.yang
src/yang/ietf-bgp-rib-types.yang
src/yang/ietf-bgp-rib.yang
src/yang/ietf-bgp.yang

From tools.ietf.org to datatracker.ietf.org

Updated the WG Web URL.

---

src/yang/ietf-bgp-capabilities.yang
src/yang/ietf-bgp-common-multiprotocol.yang
src/yang/ietf-bgp-rib.yang

Fixes issue #358. For details see the issue.

Fix when statement to use derived-from-or-self()

---

src/download-dependent-models.py

Update draft to take it out of expired state.
