src/yang/ietf-bgp-policy.yang
This PR addresses two main YANG doctor's review comments
- It addresses the question of using case statement to model set-community and set-ext-community actions. Please check that I have not changed the logic in any material way.
- Adds a leaf and a set of actions one can perform for community-count and as-path-length.
=> Addressing Yang doctors review

draft/draft-ietf-idr-bgp-model.xml, src/download-dependent-models.py, src/validate-and-gen-trees.sh, src/yang/ietf-bgp-common-structure.yang, src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp-policy.yang, src/yang/ietf-bgp.yang
Most of the changes are related to getting the draft to "compile" with the latest version of xml2rfc and to deal with changes in models that this model depends on, e.g. ietf-routing-policy.
The remaining changes are tooling changes, and they relate mostly to the strict changes that yanglint has imposed.
=> Address issue#76

Dockerfile, README.md, src/download-dependent-models.py, src/validate-and-gen-trees.sh, start.sh
This commit introduces a method by which this draft can be "build" using a container. The only requirement from a tool perspective is that the machine where this repository has been cloned has Docker installed.
The rest of the process involves copying the files over to the container to "build" the draft. To copy the result of what is build, i.e. the draft, just type the following command.
docker cp <containerId>:/file/path/within/container /host/path/target
=> How to "build" BGP draft using a container

src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp.yang
After the discussion that resulted in RFC9127-bis in BFD, the fix here
is to simply move the grouping to the transport parameters.
=> Issue 86: Per-client bfd configuration

src/yang/ietf-bgp-commands.yang, src/yang/ietf-bgp-policy.yang, src/yang/ietf-bgp-rib.yang, src/yang/ietf-bgp-types.yang
Add large bgp communities to models
Incidentally also fix an issue with extended communities to not include
the well known regular community types.
Closes #80
=> Issue 80: Add large bgp communities to models.

src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp-types.yang
=> Issue-145: Make send-community use an identity rather than bits for long term extensibility

draft/Makefile, draft/draft-ietf-idr-bgp-model.xml, src/validate-and-gen-trees.sh, src/yang/example-bgp-configuration-a.1.1.xml, src/yang/example-bgp-configuration-a.1.2.xml, src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp-neighbor.yang, src/yang/ietf-bgp-rib-tables.yang, src/yang/ietf-bgp-rib.yang, src/yang/ietf-bgp.yang
This PR addresses item #87. It adds a description statement under every use of the 'clear-route' grouping as to what it is clearing.
What was discussed on the call did not include what happens with ipv* adj-rib-in-post. Added a 'clear-route' option for that also.
Finally, refactored the grouping ipv*-loc-rib and ipv*-adj-rib grouping out as it was being used only once.
=> Clarify clear-route action

src/yang/ietf-bgp.yang
Remove ipsec configuration for the time being.  It's not widely supported in the current semantic.
Closes #59
=> Issue 59: Remove ipsec case from secure transport

draft/draft-ietf-idr-bgp-model.xml, src/validate-and-gen-trees.sh, src/yang/example-bgp-configuration-a.1.4.xml, src/yang/ietf-bgp-policy.yang
This is my attempt to add a example on how to configure a policy using the BGP policy model.
The specific example that I am trying to follow is documented at:
https://community.cisco.com/t5/networking-documents/bgp-match-community-quot-statement-used-in-route-map/ta-p/3149898
I have several questions on this example. 
- How is the policy attached? Is it through the apply-policy->import-policy or apply-policy->export-policy?
- Is a (bgp)-defined-set the same as a route-map?
- How is prefix-mode decided?
- What should the masklength-range be in this case?
- route-map includes a 'set community' command? But 'set-community' under 'actions' has a 'community-set-ref' which points back to 'community-set'. Does it mean that I should be defining 11:11 as a community-set?
- What would be a good …
=> Add a policy example

src/yang/example-bgp-configuration-a.1.4.xml, src/yang/ietf-bgp-policy.yang
As currently defined, prefix-sets are not a child of bgp-defined-sets, and prefixes are not a child of list prefix-set. 
The former I believe should be a child, unless we believe that the prefix-sets can be used outside of bgp(-defined-sets). The latter I believe leads to a prefix-set definition that contains no prefixes.
But since these code was reviewed before, and these changes are coming at the last minute, I want us to be careful reviewing this change before accepting it.
=> Fix prefix set definition and the corresponding match

draft/Makefile, draft/draft-ietf-idr-bgp-model.xml, src/validate-and-gen-trees.sh, src/yang/example-bgp-configuration-a.1.0.xml, src/yang/example-bgp-configuration-a.1.1.xml, src/yang/example-bgp-configuration-a.1.2.xml, src/yang/example-bgp-configuration-a.1.3.xml, src/yang/example-bgp-configuration-a.1.4.xml, src/yang/example-newafi-bgp.yang, src/yang/iana-bgp-types.yang, src/yang/ietf-bgp-common-multiprotocol.yang, src/yang/ietf-bgp-common-structure.yang, src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp-neighbor.yang, src/yang/ietf-bgp-policy.yang, src/yang/ietf-bgp-rib-attributes.yang, src/yang/ietf-bgp-rib-tables.yang, src/yang/ietf-bgp-rib.yang, src/yang/ietf-bgp.yang
This PR addresses the issue of how to make the ext-community-type extensible. It does it by
- adding a string definition called 'raw', that allows for new and experimental sub-types to be defined, and the 'raw' string is followed by 8 bytes of hex values.
- moving the module to a IANA maintained module.
=> How to maintain extended-community datatype

draft/draft-ietf-idr-bgp-model.xml, src/yang/example-bgp-configuration-a.1.5.xml, src/yang/ietf-bgp-policy.yang
summary of change:
added references
for community, changed type from union to string only
removed next-hop-in-eq since there is match-next-hop-set
changed afi-safi-in and neighbor-eq to container with match-set-options
changed as-path-prepend to allow any ASN prepending
=> V14 policy

src/yang/ietf-bgp-neighbor.yang, src/yang/ietf-bgp.yang
Sometime in draft-06, the BGP sent/received message counters were created in a grouping.  This grouping was then included in a local sent/received set of sub-containers.  This structure was incorrect.
Move the counters into ietf-bgp.yang, delete the grouping.
Fix a "thsi" typo in those containers.
=> Issue 236 - Fix message counters and a typo

draft/draft-ietf-idr-bgp-model.xml, src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp-policy.yang, src/yang/ietf-bgp-rib-attributes.yang, src/yang/ietf-bgp-rib-tables.yang, src/yang/ietf-bgp-rib.yang, src/yang/ietf-bgp.yang
- Correct various typos
- Normalize capitalization of RIBs in the descriptive text.
- Change to ul some of the manually created lists.
- Unroll the list of features supported in "Structure of the YANG module"
section so you can read it and it's not one long messy paragraph.
- Rename bgp-as-path-attr to bgp-as-path-segment to properly reflect its
purpose.
- Rearrange ietf-bgp-rib-attributes nodes to group community related stuff
together.
- In several places update the objects to be about "bgp routes" rather than
updates. Updates carry routes.
- Heavily re-arrange the attr-set-attributes to put them largely in RFC code
point order, but mostly do more logical grouping of several of the leaves.
Closes #247
=> Issue 247 - misc. cleanup for v16

src/yang/ietf-bgp.yang
Pull erroneous-update-messages out of general neighbors hierarchy and move to the statistics.  While doing so, rename it as "erronenous-updates-withdrawn". Do this because we also want to track the "attribute-discard" behavior covered by RFC 7606 as well.
Closes #260
=> Issue #260 - Clean up RFC 7606 related leafs

src/yang/iana-bgp-types.yang, src/yang/ietf-bgp-rib.yang
Change the aggregator "address" and cluster-list entries to use type dotted-quad.  These elements want to use a BGP Identifier for their contents. The ipv4-address type includes the scoped address case, which is inappropriate for those leaves.
Secondarily, change aggregate leaf "address" to "identifier" to more correctly reflect that this isn't an IP address.
Closes #243
=> Issue #243 - Don't use ipv4-address type for things that want dotted-quad

src/yang/ietf-bgp.yang
Removed the redundant fsm-established-transitions.
Rename peer-fsm-established-transitions to established-transitions.  This is consistent with the OpenConfig leaf.  Also, update the reference.
Closes #252
=> Issue #252 - Clean up established-transitions statistic

src/yang/example-bgp-configuration-a.1.2.xml
The example had a reference to a crypto algorithm that TCP-AO needs and was at a time defined in the TCP YANG module. Instead, it should be using the crypto algorithms already defined in ietf-key-chain model.
Address issue #267
=> Fix example a.1.2

draft/draft-ietf-idr-bgp-model.xml, src/yang/ietf-bgp-policy.yang
Per the issue, we need a format for our regular expressions.  Start with one similar to that of RPSL.
The supplied patch is too lose from a formal language perspective to make people happy long-term, but is enough to start IETF discussion.
An ABNF section will be added at a later date.
Closes #228
=> Issue #228 - A BGP YANG regular expression syntax

src/yang/example-bgp-configuration-a.1.1.xml, src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp.yang
There was a redundant bfd container left after cleanup. It has been removed. 
bgp/[...]/transport/local-address appears redundant, but in the current model it is used to configure the local-address.  The
bgp/neighbors/transport/local-address is currently operational-only state.
Removed the bgp/interfaces container.
Moved the local-address node up to the top of transport.
Closes #253
Closes #251
=> Issue #253 - Remove redundant bfd container, change local-address

src/yang/example-bgp-configuration-a.1.2.xml, src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp.yang
Issue #255 Address structure of secure-session
The enabled boolean didn't reside in the container with the secure-session
parameters themselves.  The constraint on the existing options had a constraint
that you couldn't configure options without setting the enabled status to true.
This is the opposite of how you'd normally want this to operate.
Move the enabled into the secure-session container.
Create a must constraint that when enabled, options MUST be configured.
To support the must constraint, put the current choice option into new container "options" to provide a XPath testable element.
Move secure-session into the transport container and remove redundant copy under peer-groups.
Fix the examples using secure-session.
Closes #255
=> Issue #255 Address structure of secure-session

src/yang/ietf-bgp-common-structure.yang
A useful feature in OC, added for parity.
Closes #296
=> Issue #296 - Add "disable-peer-as-filter" leaf to the as-options.

src/yang/ietf-bgp-rib.yang
The attr-set grouping was only referred to by attr-sets.  Moved its contents into attr-sets.
Closes #256
=> Issue #256 - flatten attr-set into attr-sets

src/yang/ietf-bgp.yang
This became a dangling reference in recent work.  Removed.
Closes #304
=> Issue #304 - remove ietf-interfaces from ietf-bgp.yang

src/yang/ietf-bgp-common-structure.yang, src/yang/ietf-bgp.yang
The treat-as-withdraw configuration was only in bgp/neighbors and needs also to be in bgp/peer-groups
Closes #298
=> Issue #298 - Make treat-as-withdraw group and neighbor common.

src/yang/ietf-bgp-policy.yang
Replace exact matches for local-pref-eq and med-eq with full <=, >=, = operations.
Closes #245
=> Issue #245 - policy inequality match for local-pref and med

draft/Makefile, draft/draft-ietf-idr-bgp-model.xml, src/yang/iana-bgp-types.yang, src/yang/ietf-bgp-capabilities.yang, src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp-policy.yang, src/yang/ietf-bgp.yang
The OC-inherited model only showed "negotiated capabilities".  There's an operational need to be able to show the sent/received capabilities and their capability-specific data.
Closes #248
=> Issue #248 - Restructure BGP capability state.

draft/Makefile, draft/draft-ietf-idr-bgp-model.xml, src/yang/iana-bgp-notification.yang, src/yang/ietf-bgp.yang
The old style RFC 4273 MIB stuff wasn't great, even for MIBs. Using inspiration from the OpenConfig identities, created a new sub-module for the hierarchy of BGP notification codes and sub-codes. Unlike the OC version, it's all anchored at a common root.  Most of the size of this module is providing the normative references for what the identity actually means.
Similarly, the model needs to carry the error-code and subcode for situations where the identity doesn't provide sufficient information.
The notification data and time are also added to this state.
The YANG notifications for the established and backward-transition state are similarly cleaned up and removed things that came directly from RFC 4273 that weren't particularly helpful.  As part of that work, the backwards-transition …
=> Issue #249 - Better operational state for errors

src/yang/ietf-bgp-neighbor.yang, src/yang/ietf-bgp.yang
Audit counter types and make them appropriate counter/gauge types. In general, make all counters 32 bit counters.  BGP even over long lifespan and high scale shouldn't be having things that exceed a 32 bit counter.
Closes #291
=> Issue #291 Adjust counter types

src/yang/ietf-bgp-common-structure.yang, src/yang/ietf-bgp.yang
Many implementations of BGP support dynamic peers.  Most tend to configure it from peer-group scope.  This commit adds dynamic peers as a grouping that is used at the per-group scope.  Its structure is a container with a single list where the prefixes of the peers are configured.
While this modeling is mostly empty space, it enables two flavors of extensibility:
1. The list keyed by prefix can have additional per-prefix configuration.  This accommodates features in some vendors to further restrict peers on a per-prefix basis.
2. The empty container allows per-container augmentation as well.
If an implementation prefers to model this similar to OpenConfig with a top-level bgp dynamic peers container, this grouping can be augmented in at the global level to provide naming consistency. …
=> Issue #309 Dynamic peers feature

src/yang/iana-bgp-types.yang, src/yang/ietf-bgp.yang
Based on high level survey of several implementations, make a recommendation
that we'll use a subset of POSIX.2 Extended Regular Expressions.  This may
still be too expressive for some implementations, but should be implementable
using POSIX regex().
I suspect this will get some contentious discussion in the IETF IDR Working Group.
=> Issue #53 Document a community regular expression format

src/yang/ietf-bgp-common-structure.yang, src/yang/ietf-bgp-common.yang, src/yang/ietf-bgp-neighbor.yang, src/yang/ietf-bgp.yang
grouping neighbor-group-config is used in exactly the same places that grouping neighbor-and-peer-group-common are used, so they're really the same thing.
Eliminate neighbor-group config.  This required restructuring some of the dependencies of the submodules.
Note that this causes the graceful-restart config and state to bubble down in the hierarchy where used in the neighbors and peer-groups.
Closes #281
=> Issue #281 Eliminate grouping neighbor-group-config

src/yang/ietf-bgp.yang
Issue #281's merge broke this feature.  Restored at peer-group scope.
Closes #333
=> Issue #333 Fix broken dynamic-peers usage

src/yang/ietf-bgp-common-structure.yang, src/yang/ietf-bgp-common.yang
=> Drop grouping for structure-neighbor-group-logging-options

src/yang/ietf-bgp-common-structure.yang
Deployed implementations of BGP route-reflectors are highly inconsistent about their support for "no-client-reflect".  Since the set of if-features necessary to represent the whole set of deployed behaviors would unnecessarily complicate the model, remove the feature for the time being.
Closes #242
=> Issue #242 - Remove no-client reflect.
